// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN7UtDi34SDMF-6Hz_IIOaDA7VFrrMq64',
    appId: '1:50292431716:android:dd63cc8340f28f3954f871',
    messagingSenderId: '50292431716',
    projectId: 'carbonedge-3df44',
    storageBucket: 'carbonedge-3df44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-8SBSdiOrLJLrlCs2Ui9Jan5KngFbHiQ',
    appId: '1:50292431716:ios:6c7b5d7441bd0b0254f871',
    messagingSenderId: '50292431716',
    projectId: 'carbonedge-3df44',
    storageBucket: 'carbonedge-3df44.firebasestorage.app',
    iosBundleId: 'com.example.carbonedge',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ZUp7MweGn-_pmbR6E9IMCBXLFXdz0bg',
    appId: '1:50292431716:web:3cc27b998cc6eabd54f871',
    messagingSenderId: '50292431716',
    projectId: 'carbonedge-3df44',
    authDomain: 'carbonedge-3df44.firebaseapp.com',
    storageBucket: 'carbonedge-3df44.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-8SBSdiOrLJLrlCs2Ui9Jan5KngFbHiQ',
    appId: '1:50292431716:ios:6c7b5d7441bd0b0254f871',
    messagingSenderId: '50292431716',
    projectId: 'carbonedge-3df44',
    storageBucket: 'carbonedge-3df44.firebasestorage.app',
    iosBundleId: 'com.example.carbonedge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7ZUp7MweGn-_pmbR6E9IMCBXLFXdz0bg',
    appId: '1:50292431716:web:80b77b10f7ef0ccd54f871',
    messagingSenderId: '50292431716',
    projectId: 'carbonedge-3df44',
    authDomain: 'carbonedge-3df44.firebaseapp.com',
    storageBucket: 'carbonedge-3df44.firebasestorage.app',
  );

}